### ISSUE TITLE
Problem with installed pillow version

### ISSUE THREAD

**Issue by finkf** [cisocrgroup/ocrd_cis#25]
I do `rm -rf venv && python3 -m venv venv` from inside ocrd_cis. Then `source venv/bin/activate && pip install --upgrade pip -e .`

`pip freeze | grep -i Pillow` produces: `Pillow==5.4.1`

When I run `ocrd-cis-ocropy-binarize` I get the following error:
```
Traceback (most recent call last):
  File "/nfs/datb/histocrdata/ocrd/experiments/ocrd_cis/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/nfs/datb/histocrdata/ocrd/experiments/ocrd_cis/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/nfs/datb/histocrdata/ocrd/experiments/ocrd_cis/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Pillow 5.4.1 (/nfs/datb/histocrdata/ocrd/experiments/ocrd_cis/venv/lib/python3.6/site-packages), Requirement.parse('pillow>=6.2.0'), {'ocrd-cis'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/datb/histocrdata/ocrd/experiments/ocrd_cis/venv/bin/ocrd-cis-ocropy-binarize", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/nfs/datb/histocrdata/ocrd/experiments/ocrd_cis/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/nfs/datb/histocrdata/ocrd/experiments/ocrd_cis/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/nfs/datb/histocrdata/ocrd/experiments/ocrd_cis/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/nfs/datb/histocrdata/ocrd/experiments/ocrd_cis/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/nfs/datb/histocrdata/ocrd/experiments/ocrd_cis/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/nfs/datb/histocrdata/ocrd/experiments/ocrd_cis/venv/lib64/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pillow>=6.2.0' distribution was not found and is required by ocrd-cis
```

**Comment by finkf** [comment]
@bertsky can you reproduces this error?

**Comment by finkf** [comment]
My bad. Fixed
