### ISSUE TITLE
Bad argument in function `pointPolygonTest` - pt[0] has a wrong type.

### ISSUE THREAD

**Issue by MehmedGIT** [cisocrgroup/ocrd_cis#97]
The error happened with 5 workspaces I have tried. It's strange that our test workspace still works (probably due to missing segmentation features). I am using the latest ocrd_all maximum image. Workspace used: https://gdz.sub.uni-goettingen.de/mets/PPN1023134829.mets.xml

```
N E X T F L O W  ~  version 21.04.3                                  
Launching `/scratch1/users/mmustaf/operandi/slurm_workspaces/eda2f2cc-dec8-4d5b-9da9-6267663ec455/user_workflow.nf` [prickly_bartik] - revision: d87a716c22
O P E R A N D I - H P C - D E F A U L T  P I P E L I N E
===========================================
input_file_group    : MAX
mets                : /scratch1/users/mmustaf/operandi/slurm_workspaces/eda2f2cc-dec8-4d5b-9da9-6267663ec455/cccdfe69-b449-4367-9eea-66e16e3050fa/mets.xml
volume_map_dir      : /scratch1/users/mmustaf/operandi/slurm_workspaces/eda2f2cc-dec8-4d5b-9da9-6267663ec455
models_mapping      : /scratch1/users/mmustaf/ocrd_models:/usr/local/share
sif_path            : /scratch1/users/mmustaf/ocrd_all_maximum_image.sif
singularity_wrapper : singularity exec --bind /scratch1/users/mmustaf/operandi/slurm_workspaces/eda2f2cc-dec8-4d5b-9da9-6267663ec455 --bind /scratch1/users/mmustaf/ocrd_models:/usr/local/share --env OCRD_METS_CACHING=true /scratch1/users/mmustaf/ocrd_all_maximum_image.sif

[0c/9d6c01] Submitted process > ocrd_cis_ocropy_binarize
[75/78eb46] Submitted process > ocrd_anybaseocr_crop
[45/e1c09c] Submitted process > ocrd_skimage_binarize
[c6/c6a10d] Submitted process > ocrd_skimage_denoise
[74/b99277] Submitted process > ocrd_tesserocr_deskew
[6b/214ea6] Submitted process > ocrd_cis_ocropy_segment
Error executing process > 'ocrd_cis_ocropy_segment'

Caused by:
  Process `ocrd_cis_ocropy_segment` terminated with an error exit status (1)

Command executed:

  singularity exec --bind /scratch1/users/mmustaf/operandi/slurm_workspaces/eda2f2cc-dec8-4d5b-9da9-6267663ec455 --bind /scratch1/users/mmustaf/ocrd_models:/usr/local/share --env OCRD_METS_CACHING=true /scratch1/users/mmustaf/ocrd_all_maximum_image.sif ocrd-cis-ocropy-segment -m mets.xml -I OCR-D-BIN-DENOISE-DESKEW -O OCR-D-SEG -p '{"level-of-operation": "page"}'

Command exit status:
  1

Command output:
  (empty)

Command error:
  13:38:12.729 INFO processor.OcropySegment - Found 20 separators for page "FILE_0001_OCR-D-BIN-DENOISE-DESKEW"
  13:38:12.767 ERROR ocrd.processor.helpers.run_processor - Failure in processor 'ocrd-cis-ocropy-segment'
  Traceback (most recent call last):
    File "/build/core/ocrd/ocrd/processor/helpers.py", line 128, in run_processor
      processor.process()
    File "/usr/local/lib/python3.8/site-packages/ocrd_cis/ocropy/segment.py", line 404, in process
      self._process_element(page, ignore, page_image, page_coords,
    File "/usr/local/lib/python3.8/site-packages/ocrd_cis/ocropy/segment.py", line 750, in _process_element
      sep_polygons, _ = masks2polygons(seplines, None, element_bin,
    File "/usr/local/lib/python3.8/site-packages/ocrd_cis/ocropy/segment.py", line 139, in masks2polygons
      hole_idx = np.argmin([cv2.pointPolygonTest(contour, tuple(pt[0]), True)
    File "/usr/local/lib/python3.8/site-packages/ocrd_cis/ocropy/segment.py", line 139, in <listcomp>
      hole_idx = np.argmin([cv2.pointPolygonTest(contour, tuple(pt[0]), True)
  cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'pointPolygonTest'
  > Overload resolution failed:
  >  - Can't parse 'pt'. Sequence item with index 0 has a wrong type
  >  - Can't parse 'pt'. Sequence item with index 0 has a wrong type
  
  Traceback (most recent call last):
    File "/usr/local/bin/ocrd-cis-ocropy-segment", line 8, in <module>
      sys.exit(ocrd_cis_ocropy_segment())
    File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
      return self.main(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
      rv = self.invoke(ctx)
    File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
      return __callback(*args, **kwargs)
    File "/usr/local/lib/python3.8/site-packages/ocrd_cis/ocropy/cli.py", line 53, in ocrd_cis_ocropy_segment
      return ocrd_cli_wrap_processor(OcropySegment, *args, **kwargs)
    File "/build/core/ocrd/ocrd/decorators/__init__.py", line 116, in ocrd_cli_wrap_processor
      run_processor(processorClass, mets_url=mets, workspace=workspace, **kwargs)
    File "/build/core/ocrd/ocrd/processor/helpers.py", line 131, in run_processor
      raise err
    File "/build/core/ocrd/ocrd/processor/helpers.py", line 128, in run_processor
      processor.process()
    File "/usr/local/lib/python3.8/site-packages/ocrd_cis/ocropy/segment.py", line 404, in process
      self._process_element(page, ignore, page_image, page_coords,
    File "/usr/local/lib/python3.8/site-packages/ocrd_cis/ocropy/segment.py", line 750, in _process_element
      sep_polygons, _ = masks2polygons(seplines, None, element_bin,
    File "/usr/local/lib/python3.8/site-packages/ocrd_cis/ocropy/segment.py", line 139, in masks2polygons
      hole_idx = np.argmin([cv2.pointPolygonTest(contour, tuple(pt[0]), True)
    File "/usr/local/lib/python3.8/site-packages/ocrd_cis/ocropy/segment.py", line 139, in <listcomp>
      hole_idx = np.argmin([cv2.pointPolygonTest(contour, tuple(pt[0]), True)
  cv2.error: OpenCV(4.7.0) :-1: error: (-5:Bad argument) in function 'pointPolygonTest'
  > Overload resolution failed:
  >  - Can't parse 'pt'. Sequence item with index 0 has a wrong type
  >  - Can't parse 'pt'. Sequence item with index 0 has a wrong type

```

**Comment by bertsky** [comment]
This is a regression caused by Numpy 1.24 changes. There are many more such incompatibilities, which also cause trouble in other processors. That's why we have tried to hold/downgrade Numpy in ocrd_all. Please check the Numpy version. Or try with the most recent version of #87 (which does include adaptations for upstream Numpy and Shapely).

**Comment by MehmedGIT** [comment]
Thanks. Do you know if the most recent version will be part of the upcoming ocrd_all releases?

**Comment by bertsky** [comment]
> Do you know if the most recent version will be part of the upcoming ocrd_all releases?

Yes, as long as #87 is not finished, ocrd_all will simply have to keep updating from that branch.

**Comment by MehmedGIT** [comment]
This is fixed and part of the ocrd/all:2023-06-18.
